#remote_theme         : ''
#theme                : minimal-mistakes-jekyll

plugins:
  - jekyll-paginate
  - jekyll-sitemap
  - jekyll-gist
  - jekyll-feed
  - jemoji
  - jekyll-include-cache

  #    ______            __             __     _____      __  __  _                 
#   / ____/___  ____  / /_____ ______/ /_   / ___/___  / /_/ /_(_)___  ____ ______
#  / /   / __ \/ __ \/ __/ __ `/ ___/ __/   \__ \/ _ \/ __/ __/ / __ \/ __ `/ ___/
# / /___/ /_/ / / / / /_/ /_/ / /__/ /_    ___/ /  __/ /_/ /_/ / / / / /_/ (__  ) 
# \____/\____/_/ /_/\__/\__,_/\___/\__/   /____/\___/\__/\__/_/_/ /_/\__, /____/  
#                                                                   /____/        

contact:
  endpoint: "https://formspree.io/f/mgepqbvj"
  recaptcha:
    sitekey: "6Lc-4FAaAAAAAGS6NB2VzIPW6DS_qsOzf8mID6iQ"
