#baseurl:            ""
#url:                "https://gpaulissen.github.io"
github_username:    gpaulissen
timezone:           UTC+1
locale:             en_GB
#permalink:          /:year/:month/:day/:title/
exclude:            [vendor]

theme: jekyll-theme-cayman